foodgramm/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.flatpages import views as views_flat

from . import views

handler404 = 'foodgramm.views.page_not_found'
handler500 = 'foodgramm.views.server_error'

urlpatterns = [
    path('404/', views.page_not_found),
    path('500/', views.server_error),
    path('admin/', admin.site.urls),
    path("", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path('', include("recipes.urls")),
]
urlpatterns += [
    path('about-me/', views_flat.flatpage, {'url': '/about-me/'}, name='about'),
    path('stack/', views_flat.flatpage, {'url': '/stack/'}, name='stack'),
]

posts/urls.py
from django.urls import path
from .views import Ingredients, add_recipe, post_view,\
    RecipeEdit, RecipeDelete, Subscriptions, single_page, ProfileUser, index

app_name = 'posts'

urlpatterns = [

    path('', index, name="index"),
    path('subscriptions', Subscriptions.as_view(),
         name='add_subscriptions_url'),
    path('api/v1/ingredients', Ingredients.as_view(), name='API'),
    path("add_recipe/", add_recipe, name="add_recipe"),
    path('about/', single_page, name='single_page_about'),
    path("stack/", single_page, name="single_page_stack_url"),
    path("<slug>", post_view, name="post_url"),
    path('<str:slug>/edit/', RecipeEdit.as_view(),
         name='edit_recipes_url'),
    path('<str:slug>/delete/', RecipeDelete.as_view(),
         name='delete_recipes_url'),
    path('author/<str:username>/', ProfileUser.as_view(),
         name='author_url'),
    path('subscriptions/<int:id>/', Subscriptions.as_view(),
         name='del_subscriptions_url'),

]

recipes/urls.py
from django.urls import path

from .views import (Ingredients, ProfileUser, RecipeDelete, RecipeEdit,
                    Subscriptions, add_recipe, index, post_view)

app_name = 'recipes'

urlpatterns = [

    path('', index, name="index"),
    path('subscriptions', Subscriptions.as_view(),
         name='add_subscriptions_url'),
    path('api/v1/ingredients', Ingredients.as_view(), name='API'),
    path("add_recipe/", add_recipe, name="add_recipe"),
    path("<slug:slug>", post_view, name="post_url"),
    path('<str:slug>/edit/', RecipeEdit.as_view(),
         name='edit_recipes_url'),
    path('<str:slug>/delete/', RecipeDelete.as_view(),
         name='delete_recipes_url'),
    path('author/<str:username>/', ProfileUser.as_view(),
         name='author_url'),
    path('subscriptions/<int:id>/', Subscriptions.as_view(),
         name='del_subscriptions_url'),

]

urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

templates/authorRecipe.html
{% extends "base.html" %} 
{% block title %} Автор {% endblock %}
{% load user_filters %}
{% load static %}
{% block style %} <link rel="stylesheet" href={% static "/pages/index.css" %}>{% endblock %}
{% block content %}
<div class="main__header">
    <h1 class="main__title">Вероника Чернова</h1>
    <ul class="tags">
        <li class="tags__item">
            <a id="breakfast" class="tags__checkbox tags__checkbox_style_orange tags__checkbox_active" href="#"></a>
            <span class="tags__label">Завтрак</span>
        </li>
        <li class="tags__item">
            <a id="lunch" class="tags__checkbox tags__checkbox_style_green tags__checkbox_active" href="#"></a>
            <span for="lunch" class="tags__label">Обед</span>
        </li>
        <li class="tags__item">
            <a id="dinner" class="tags__checkbox tags__checkbox_style_purple tags__checkbox_active" href="#"></a>
            <label for="dinner" class="tags__label">Ужин</label>
        </li>
    </ul>

</div>
<!--        <p style="padding: 0 0 2em 0;"><a class="button button_style_light-blue" href="#">Подписаться на автора</a></p>-->
<div class="author-subscribe" data-author="323">
    <p style="padding: 0 0 2em 0;"><button class="button button_style_light-blue button_size_subscribe" name="subscribe" data-out>Подписаться на автора</button></p>
</div>
<div class="card-list" >
<div class="card" data-id="120">
    <a href="#" class="link" target="_blank"><img src="../media/testCardImg.png" alt="Какой-то текст" class="card__image"></a>
    <div class="card__body">
        <a class="card__title link" href="#" target="_blank">Французские тосты</a>
        <ul class="card__items">
            <li class="card__item"><span class="badge badge_style_green">Обед</span></li>
            <li class="card__item"><span class="badge badge_style_orange">Завтрак</span></li>
            <li class="card__item"><span class="badge badge_style_purple">Ужин</span></li>
        </ul>
        <div class="card__items card__items_column">
            <p class="card__text"><span class="icon-time"></span> 20 мин.</p>
            <p class="card__text"><span class="icon-user"></span> <a href="#" style="color: black">Вероника Чернова</a></p>
        </div>
    </div>
    <div class="card__footer">
        <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>
        <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite"></span></button>
    </div>
</div>
<div class="card" data-id="121">
    <a href="#" class="link" target="_blank"><img src="../media/testCardImg.png" alt="Какой-то текст" class="card__image"></a>
    <div class="card__body">
        <a class="card__title link" href="#" target="_blank">Французские тосты</a>
        <ul class="card__items">
            <li class="card__item"><span class="badge badge_style_green">Обед</span></li>
            <li class="card__item"><span class="badge badge_style_orange">Завтрак</span></li>
            <li class="card__item"><span class="badge badge_style_purple">Ужин</span></li>
        </ul>
        <div class="card__items card__items_column">
            <p class="card__text"><span class="icon-time"></span> 20 мин.</p>
            <p class="card__text"><span class="icon-user"></span> <a href="#" style="color: black">Вероника Чернова</a></p>
        </div>
    </div>
    <div class="card__footer">
        <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>
        <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite"></span></button>
    </div>
</div>
<div class="card" data-id="122">
    <a href="#" class="link" target="_blank"><img src="../media/testCardImg.png" alt="Какой-то текст" class="card__image"></a>
    <div class="card__body">
        <a class="card__title link" href="#" target="_blank">Французские тосты</a>
        <ul class="card__items">
            <li class="card__item"><span class="badge badge_style_green">Обед</span></li>
            <li class="card__item"><span class="badge badge_style_orange">Завтрак</span></li>
            <li class="card__item"><span class="badge badge_style_purple">Ужин</span></li>
        </ul>
        <div class="card__items card__items_column">
            <p class="card__text"><span class="icon-time"></span> 20 мин.</p>
            <p class="card__text"><span class="icon-user"></span> <a href="#" style="color: black">Вероника Чернова</a></p>
        </div>
    </div>
    <div class="card__footer">
        <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>
        <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite"></span></button>
    </div>
</div>
<div class="card" data-id="123">
    <a href="#" class="link" target="_blank"><img src="../media/testCardImg.png" alt="Какой-то текст" class="card__image"></a>
    <div class="card__body">
        <a class="card__title link" href="#" target="_blank">Французские тосты</a>
        <ul class="card__items">
            <li class="card__item"><span class="badge badge_style_green">Обед</span></li>
            <li class="card__item"><span class="badge badge_style_orange">Завтрак</span></li>
            <li class="card__item"><span class="badge badge_style_purple">Ужин</span></li>
        </ul>
        <div class="card__items card__items_column">
            <p class="card__text"><span class="icon-time"></span> 20 мин.</p>
            <p class="card__text"><span class="icon-user"></span> <a href="#" style="color: black">Вероника Чернова</a></p>
        </div>
    </div>
    <div class="card__footer">
        <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>
        <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite"></span></button>
    </div>
</div>
<div class="card" data-id="124">
    <a href="#" class="link" target="_blank"><img src="../media/testCardImg.png" alt="Какой-то текст" class="card__image"></a>
    <div class="card__body">
        <a class="card__title link" href="#" target="_blank">Французские тосты</a>
        <ul class="card__items">
            <li class="card__item"><span class="badge badge_style_green">Обед</span></li>
            <li class="card__item"><span class="badge badge_style_orange">Завтрак</span></li>
            <li class="card__item"><span class="badge badge_style_purple">Ужин</span></li>
        </ul>
        <div class="card__items card__items_column">
            <p class="card__text"><span class="icon-time"></span> 20 мин.</p>
            <p class="card__text"><span class="icon-user"></span> <a href="#" style="color: black">Вероника Чернова</a></p>
        </div>
    </div>
    <div class="card__footer">
        <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>
        <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite"></span></button>
    </div>
</div>
</div>
<nav class="pagination" aria-label="Search results pages">
    <ul class="pagination__container">
        <li class="pagination__item"><a class="pagination__link link" href="#"><span class="icon-left"></span></a></li>
        <li class="pagination__item pagination__item_active"><a class="pagination__link link" href="#">1</a></li>
        <li class="pagination__item"><a class="pagination__link link" href="#">2</a></li>
        <li class="pagination__item"><a class="pagination__link link" href="#">3</a></li>
        <li class="pagination__item"><a class="pagination__link link" href="#">4</a></li>
        <li class="pagination__item"><a class="pagination__link link" href="#">5</a></li>
        <li class="pagination__item"><a class="pagination__link link" href="#"><span class="icon-right"></span></a></li>
    </ul>
</nav>
</main>
{% block script %}
<script src={% static "/js/components/MainCards.js" %}></script>

<script src={% static "/js/components/Purchases.js" %}></script>
<script src={% static "/js/components/Favorites.js" %}></script>
<script src={% static "/js/components/Subscribe.js" %}></script>

<script src={% static "/js/config/config.js" %}></script>
<script src={% static "/js/components/AuthorRecipe.js" %}></script>
<script src={% static "/js/components/Header.js" %}></script>

<script src={% static "/js/api/Api.js" %}></script>
<script src={% static "authorRecipe.js" %}></script>
{% endblock %}
{% endblock %}

templates/favorite.html
{% extends "base.html" %} 
{% block title %} Избранное {% endblock %}
{% load user_filters %}
{% load recipes_extras %}
{% block my_favorites %}<li class="nav__item nav__item_active">{% endblock %}
{% load static %}
{% block style %} <link rel="stylesheet" href={% static "/pages/index.css" %}>{% endblock %}
{% block content %}
{% csrf_token %}
<div class="main__header">
    <h1 class="main__title">Избранное</h1>
    <ul class="tags">
        {% with filter_values=request.GET|get_filter_values %}
        {% for tag in all_tags %}
        <li class="tags__item">
            <a 
                id="{{ tag.value }}" 
                class="tags__checkbox tags__checkbox_style_{{ tag.style }} {% if tag.name in filter_values %}tags__checkbox_active{% endif %}" href="{% url 'my_favorites' %}?{{ request|get_filter_link:tag }}"></a>
        <span class="tags__label">{{ tag.name }}</span>     
    </li>
        {% endfor %}
        {% endwith %}
</ul>
</div>
<div class="card-list">
    {% for item in page %}
    <div class="card" data-id="{{ item.recipe.id }}">
        <a href="{% url 'recipes:post_url' item.recipe.slug %}" class="link" target="_blank"><img src="{{ item.recipe.image.url }}" alt="Фото {{ item.recipe.title }}" class="card__image"></a>
        <div class="card__body">
            <a class="card__title link" href="" target="_blank">{{ post.title }}</a>
            <ul class="card__items">
                {% for tag in item.recipe.tags.all %}
                <li class="card__item"><span class="badge badge_style_{{ tag.style }}">{{ tag.name }}</span></li>
                {% endfor %}
            </ul>
            <div class="card__items card__items_column">
                <p class="card__text"><span class="icon-time"></span> {{ item.recipe.time }} мин.</p>
                <p class="card__text"><span class="icon-user"></span> <a href="{% url 'recipes:author_url' item.recipe.author %}" style="color: black">{{ item.recipe.author }}</a></p>
            </div>
        </div>
        <div class="card__footer">
            {% if not recipe.id in buying_list %}
            <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>
        {% else %}
            <button class="button button_style_light-blue" name="purchases"><span class="icon-plus button__icon"></span>Рецепт добавлен</button>
        {% endif %}
            
        <button class="button button_style_none" name="favorites" {% if not post.id in fav_list %}data-out{% endif %}><span class="icon-favorite {% if post.id in fav_list %}icon-favorite_active{% endif %}"></span></button>      
  
        </div>
    </div>
    {% endfor %}
</div>
{% if page.has_other_pages %}
{% include 'paginator.html' %}   
 {% endif %}
</main>
{% endblock %}
{% block script %}
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/Purchases.js' %}"></script>
{% if user.is_authenticated %}
<script src="{% static 'js/components/Favorites.js' %}"></script>
<script src="{% static 'js/components/Subscribe.js' %}"></script>
<script src="{% static 'js/components/CardList.js' %}"></script>    
<script src="{% static 'indexAuth.js' %}"></script>
{% else %}
<script src="{% static 'indexNotAuth.js' %}"></script>
{% endif %}
<script src="{% static 'js/components/MainCards.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
{% endblock %}

templates/footer.html
<footer class="footer">
    <div class="footer__container container">
        <a href="{% url 'recipes:index' %}" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="{% url 'about' %}" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="{% url 'stack' %}" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>

templates/index.html
{% extends "base.html" %} 
{% block title %} Рецепты {% endblock %}
{% load user_filters %}
{% load recipes_extras %}
{% block index %}<li class="nav__item nav__item_active">{% endblock %}
{% load static %}
{% block style %}<link rel="stylesheet" href={% static "/pages/index.css" %}>{% endblock %}
{% block content %}
{% csrf_token %}
<div class="main__header">
    <h1 class="main__title">Рецепты</h1>
    <ul class="tags">
            {% with filter_values=request.GET|get_filter_values %}
            {% for tag in all_tags %}
            <li class="tags__item">
                <a 
                    id="{{ tag.value }}" 
                    class="tags__checkbox tags__checkbox_style_{{ tag.style }} {% if tag.name in filter_values %}tags__checkbox_active{% endif %}" href="{% url 'recipes:index' %}?{{ request|get_filter_link:tag }}"></a>
            <span class="tags__label">{{ tag.name }}</span>     
        </li>
            {% endfor %}
            {% endwith %}
    </ul>
</div>
<div class="card-list">
    {% for post in page %}
    <div class="card" data-id="{{ post.id }}">
        <a href="{% url 'recipes:post_url' post.slug %}" class="link" target="_blank"><img src="{{ post.image.url }}" alt="Фото {{ post.title }}" class="card__image"></a>
        <div class="card__body">
            <a class="card__title link" href="{% url 'recipes:post_url' post.slug %}" target="_blank">{{ post.title }}</a>
            <ul class="card__items">
                {% for tag in post.tags.all %}
                <li class="card__item"><span class="badge badge_style_{{ tag.style }}">{{ tag.name }}</span></li>
                {% endfor %}
            </ul>
            <div class="card__items card__items_column">
                <p class="card__text"><span class="icon-time"></span> {{ post.time }} мин.</p>
                <p class="card__text"><span class="icon-user"></span> <a href="{% url 'recipes:author_url' post.author %}" style="color: black">{{ post.author }}</a></p>
            </div>
        </div>
        {% if request.user.is_authenticated %}
        <div class="card__footer">
            <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>
            <button class="button button_style_none" name="favorites" {% if not post.id in fav_list %}data-out{% endif %}><span class="icon-favorite {% if post.id in fav_list %}icon-favorite_active{% endif %}"></span></button>
        </div>
        {% endif %}
    </div>
        {% endfor %}
</div>
{% if page.has_other_pages %}
    {% include 'paginator.html' %}   
{% endif %}
</main>
{% endblock %}
{% block script %}
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/Purchases.js' %}"></script>
<script src="{% static 'js/components/MainCards.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
{% if user.is_authenticated %}
<script src="{% static 'js/components/Favorites.js' %}"></script>
<script src="{% static 'js/components/Subscribe.js' %}"></script>
<script src="{% static 'js/components/CardList.js' %}"></script>    
<script src="{% static 'indexAuth.js' %}"></script>
{% else %}
<script src="{% static 'indexNotAuth.js' %}"></script>
{% endif %}
{% endblock %}

templates/my_subscription.html
{% extends "base.html" %} 
{% block title %} Мои подписки {% endblock %}
{% load static %}
{% block my_subscriptions %}<li class="nav__item nav__item_active">{% endblock %}
{% block style %} <link rel="stylesheet" href={% static "/pages/myFollow.css" %}>{% endblock %}
{% block content %}
{% csrf_token %}
<div class="main__header">
    <h1 class="main__title">Мои подписки</h1>
</div>
<div class="card-list">
    {% for sub in subscriptions %}
    {% with subscriptions_recipes=sub.get_recipes %}
    <div class="card-user" data-author="{{ sub.author.id }}">
    <div class="card-user__header">
        <h2 class="card-user__title">{{ sub.author }}</h2>
    </div>
    <div class="card-user__body">
        <ul class="card-user__items">
            {% for recipe in subscriptions_recipes %}
            {% if forloop.counter < 4 %}
            <li class="card-user__item">
                <div class="recipe">
                    <img src="{{ recipe.image.url }}" alt="фото {{ recipe.title }}" class="recipe__image">
                    <h3 class="recipe__title">{{ recipe.title }}</h3>
                    <p class="recipe__text"><span class="icon-time"></span> {{ recipe.time }} мин.</p>
                </div>
            </li>
            {% endif %}
            {% endfor %}
            {% if forloop.counter > 3 %}
            <li class="card-user__item">
                <a href="{% url 'recipes:author_url' sub.author.username %}" class="card-user__link link">Еще рецептов {{ subscriptions_recipes.count|add:-3 }}</a>
            </li>
            {% endif %}
        </ul>
    </div>
    <div class="card-user__footer">
        <button class="button button_style_light-blue button_size_auto" name="subscribe">Отписаться</button>
    </div>
</div>
{% endwith %}
{% endfor %}
</div>
{% if page.has_other_pages %} 
{% include 'paginator.html' with recipes=subscriptions %}   
{% endif %}
</main>
{% endblock %}
{% block script %}
<script src="{% static '/js/config/config.js' %}"></script>
<script src="{% static 'js/components/MainCards.js' %}"></script>
<script src="{% static '/js/components/MyFollow.js' %}"></script>
<script src="{% static 'js/components/Subscribe.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'myFollow.js' %}"></script>
{% endblock %}

templates/nav.html
<nav class="nav">
    <div class="nav__container container">
        {% if user.is_authenticated %}
                <ul class="nav__items list"></ul>
                    {% block index %}<li class="nav__item">{% endblock %}<a href="{% url 'recipes:index' %}" class="nav__link link">Рецепты</a></li>
                    {% block my_subscriptions %}<li class="nav__item">{% endblock %}<a href="{% url 'my_subscriptions' %}" class="nav__link link">Мои подписки</a></li>
                    {% block add_recipe %}<li class="nav__item">{% endblock %}<a href="{% url 'recipes:add_recipe' %}" class="nav__link link">Создать рецепт</a></li>
                    {% block my_favorites %}<li class="nav__item">{% endblock %}<a href="{% url 'my_favorites' %}" class="nav__link link">Избранное</a></li>
                    {% block shop_list %}<li class="nav__item">{% endblock %}<a href="{% url 'shop_list' %}" class="nav__link link">Список покупок</a> <span class="badge badge_style_blue nav__badge" id="counter">{{ purchases_count }}</span></li>
                </ul>
                <ul class="nav__items list">
                    {% block password_change %}<li class="nav__item">{% endblock %}<a href="{% url 'password_change' %}" class="nav__link link">Изменить пароль</a></li>
                    <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link link">Выход</a></li>
                </ul>
        {% else %}
        <ul class="nav__items list">
            <li class="nav__item nav__item_active"><a href="{% url 'recipes:index' %}" class="nav__link link">Рецепты</a></li>        </ul>
        <ul class="nav__items list">
            {% block login %}<li class="nav__item">{% endblock %}<a href="{% url 'login' %}" class="nav__link link">Войти</a></li>
            {% block signup %}<li class="nav__item">{% endblock %}<a href="{% url 'signup' %}" class="button button_style_blue">Создать аккаунт</a></li>
        </ul>
        {% endif %}
    </div>
</nav>

templates/post.html
{% extends "base.html" %} 
{% block title %} {{ post.title }} {% endblock %}
{% load user_filters %}
{% load static %}
{% block style %}<link rel="stylesheet" href={% static "/pages/single.css" %}>{% endblock %}
{% block content %}
{% csrf_token %}
    <main class="main container">
        <div class="single-card" data-id="{{ post.id }}" data-author="{{ post.author.id }}">
            <img src="{{ post.image.url }}" alt="Фото рецепта {{ post.title }}" class="single-card__image">
            <div class="single-card__info">
                <div class="single-card__header-info">
                    <h1 class="single-card__title">{{ post.title }}</h1>
                    {% if request.user.is_authenticated %}
                <div class="single-card__favorite">
                    <button class="button button_style_none" name="favorites" {% if not favorite %}data-out{% endif %}><span class="icon-favorite icon-favorite_big {% if fav %}icon-favorite_active{% endif %}"></span></button>

                    <div class="single-card__favorite-tooltip tooltip">Добавить в избранное</div>
                </div>
                {% endif %}
                </div>
                <ul class="single-card__items">
                    {% for tag in post.tags.all %}
                    <li class="single-card__item"><span class="badge badge_style_{{ tag.style }}">{{  tag.name }}</span></li>
                    {% endfor %}
                    {% if request.user == post.author %}<li class="single-card__item">  <a style="margin-left: 2.5em" href="{% url 'recipes:edit_recipes_url' post.slug %}" class="single-card__text">Редактировать рецепт</a></li>{% endif %}
                </ul>
                <div class="single-card__items single-card__items_column">
                    <p class="single-card__text"><span class="icon-time"></span> {{ post.time }} мин.</p>
                    <p class="single-card__text"><span class="icon-user"></span> {{ post.author.username }}</p>
                    
                </div>
                {% if user.is_authenticated %}
                <ul class="single-card__items">
                    <li class="single-card__item">
                        {% if not buying %}
                        <button class="button button_style_blue" name="purchases" data-out><span class="icon-plus"></span> Добавить в покупки</button>
                        {% else %}
                        <button class="button button_style_light-blue-outline" name="purchases"><span class="icon-check button__icon"></span> Рецепт добавлен</button>
                        {% endif %}
                    </li>
                    {% if request.user.is_authenticated %}<li class="single-card__item">
                        <button class="button button_style_light-blue button_size_auto" name="subscribe" {% if not subsc %}data-out>Подписаться на автора {% else %}>
                            <span class="icon-check button__icon"></span> Отписаться от автора{% endif %}</button></li>
               {% endif %}
               
                </ul>
                {% endif %}
                <div class="single-card__section">
                    <h3 class="single-card__section-title">Ингредиенты:</h3>
                    <div class="single-card__items single-card__items_column">
                        {% for item in post.recipe.all %}
                        <p class=" single-card__section-item">{{ item.ingredient.title }} - {{ item.units }} {{ item.ingredient.dimension }} </p>
                        {% endfor %}
                    </div>
                </div>
                <div class="single-card__section">
                    <h3 class="single-card__section-title">Описание:</h3>
                    <p class=" single-card__section-text"> {{ post.text }}</p>
                </div>
            </div>
        </div>
    </main>
{% endblock %}
{% block script %}
<script src="{% static 'js/config/config.js' %}"></script>
<script src="{% static 'js/components/Purchases.js' %}"></script>
<script src="{% static 'js/components/MainCards.js' %}"></script>
<script src="{% static 'js/components/SingleCard.js' %}"></script>
<script src="{% static 'js/components/Header.js' %}"></script>
{% if user.is_authenticated %}
<script src="{% static 'js/components/Favorites.js' %}"></script>
<script src="{% static 'js/components/Subscribe.js' %}"></script>
{% else %}
<script src="{% static 'singlePageNotAuth.js' %}"></script>
{% endif %}
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'singlePage.js' %}"></script>
{% endblock %}

templates/shopList.html
{% extends "base.html" %} 
{% block title %} Страница покупок {% endblock %}
{% load user_filters %}
{% block shop_list %}<li class="nav__item nav__item_active">{% endblock %}
{% load static %}
{% block style %} <link rel="stylesheet" href={% static "pages/shopList.css" %}>{% endblock %}
{% block content %}
{% csrf_token %}

    <div class="main__header">
        <h1 class="main__title">Список покупок</h1>
    </div>
    <div class="card-list card-list_column">
        <ul class="shopping-list">
            {% for item in purchases %}
            <li class="shopping-list__item" data-id="{{ item.recipe.id }}">
                <div class="recipe recipe_reverse">
                    <img src="{{ item.recipe.image.url }}" alt="Фото {{ item.recipe.title }}" class="recipe__image recipe__image_big">
                    <h3 class="recipe__title"><a href="{% url 'recipes:post_url' item.recipe.slug %}">{{ item.recipe.title }}</a></h3>
                    <p class="recipe__text"><span class="icon-time"></span> {{ item.recipe.time }} мин.</p>
                </div>
                <a href="{% url 'del_one_purchase' item.recipe.id %}" class="shopping-list__button link">Удалить</a>
            </li>
            {% endfor %}
            
        </ul>
        {% if purchases_count != 0 %}
        <a href="{% url 'get_shop_list_url' %}"><button class="button button_style_blue">Скачать список</button></a>
        {% endif %}
    </div>
</main>
{% endblock %}
{% block script %}
<script src="{% static 'js/components/Header.js' %}"></script>
<script src="{% static 'js/components/ShopList.js' %}"></script>
<script src="{% static 'js/api/Api.js' %}"></script>
<script src="{% static 'shopList.js' %}"></script>
{% endblock %}